<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>it.univr</groupId>
    <artifactId>codice-wally-teoria</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>es01</module>
        <module>es02</module>
        <module>es03</module>
        <module>es04</module>
        <module>es05</module>
        <module>es06</module>
        <module>es07</module>
        <module>es08</module>
        <module>es09</module>
        <module>es10</module>
        <module>es11</module>
        <module>es12</module>
        <module>es13</module>
        <module>es14</module>
        <module>es15</module>
        <module>es16</module>
        <module>es17</module>
        <module>es18</module>
        <module>es19</module>
        <module>es20</module>
        <module>es21</module>
        <module>es22</module>
        <module>es23</module>
        <module>es24</module>
        <module>es25</module>
        <module>es26</module>
        <module>es27</module>
        <module>es28</module>
        <module>es29</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>5.10.0</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
